# Generated by Django 2.1.3 on 2018-12-07 01:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_da_categoria', models.CharField(max_length=100)),
                ('Ativada', models.BooleanField()),
                ('Obs_da_categoria', models.TextField()),
                ('Data_de_cadastro_da_categoria', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente_ativo', models.BooleanField()),
                ('Nome_fantasia', models.CharField(max_length=100)),
                ('Nome_do_cliente', models.CharField(max_length=100)),
                ('Razao_social', models.CharField(max_length=100)),
                ('Logo_do_cliente', models.ImageField(upload_to='upload/')),
                ('Telefone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Telefone_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Celular_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Site_do_cliente', models.URLField()),
                ('Tipo_juridico_do_cliente', models.CharField(choices=[('MEI', 'Micro Empreendedor Individual'), ('PF', 'Pessoa Física'), ('SN', 'Simples Nacional')], max_length=50)),
                ('Cnpj', models.CharField(max_length=100)),
                ('Inscricao_estadual', models.CharField(max_length=50)),
                ('Possui_contrato', models.CharField(choices=[('SC', 'Sem contrato'), ('EN', 'Contrato em negociação'), ('PC', 'Possui contrato')], max_length=30)),
                ('Contrato_ou_proposta_anexado', models.FileField(upload_to='upload/')),
                ('Valor_total_do_contrato', models.FloatField()),
                ('Endereco', models.CharField(max_length=300)),
                ('CEP', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=60)),
                ('Estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=60)),
                ('Email_do_cliente', models.EmailField(max_length=254)),
                ('Obs_do_cliente', models.TextField()),
                ('Data_de_cadastro_do_cliente', models.DateField()),
                ('Categoria_do_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Categoria')),
            ],
        ),
    ]
